name: olgoo_mobile
description: "online management platform for clothing companies"
publish_to: 'none' 
version: 3.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  shimmer: ^3.0.0
  intl: ^0.19.0
  dio: ^5.7.0
  persian_number_utility: ^1.1.4
  marqueer: ^1.4.5
  get_it: ^8.0.0
  shared_preferences: ^2.3.2
  jwt_decoder: ^2.0.1
  equatable: ^2.0.5
  delayed_widget: ^1.1.2
  flutter_localization: ^0.2.2
  smooth_page_indicator: ^1.2.0+3
  go_router: ^14.2.8
  pinput: ^5.0.0
  toastification: ^2.3.0
  flutter_dash: ^1.0.0
  dotted_border: ^2.1.0
  loading_animation_widget: ^1.3.0
  fl_chart: ^0.69.0
  percent_indicator: ^4.2.4
  expandable: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/img/
    - assets/svgs/
  fonts:
    - family: dana
      fonts:
        - asset: assets/fonts/Light.ttf
          weight: 200        
        - asset: assets/fonts/Regular.ttf
          weight: 300          
        - asset: assets/fonts/Medium.ttf
          weight: 500        
        - asset: assets/fonts/DemiBold.ttf
          weight: 700 
        - asset: assets/fonts/Bold.ttf
          weight: 800
